### ISSUE TITLE
Ignores Breakpoints in Debugging 

### ISSUE THREAD

**Issue by daimor** [intersystems-community/vscode-objectscript#1030]
When the extension works alone, without Language Server, it fails with error
<img width="487" alt="image" src="https://user-images.githubusercontent.com/1212251/207669357-f100e38a-2324-44b8-861b-c9fad4c604d6.png">

```
2022-12-14 21:45:06.758 [error] [intersystems-community.vscode-objectscript] provider FAILED
2022-12-14 21:45:06.758 [error] TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at t.Formatter.setCase (/Users/daimor/.vscode/extensions/intersystems-community.vscode-objectscript-2.2.0/dist/extension.js:2:614185)
    at /Users/daimor/.vscode/extensions/intersystems-community.vscode-objectscript-2.2.0/dist/extension.js:2:614678
    at String.replace (<anonymous>)
    at t.Formatter.command (/Users/daimor/.vscode/extensions/intersystems-community.vscode-objectscript-2.2.0/dist/extension.js:2:614648)
    at /Users/daimor/.vscode/extensions/intersystems-community.vscode-objectscript-2.2.0/dist/extension.js:2:622121
    at Array.map (<anonymous>)
    at t.ObjectScriptCompletionItemProvider.commands (/Users/daimor/.vscode/extensions/intersystems-community.vscode-objectscript-2.2.0/dist/extension.js:2:622084)
    at t.ObjectScriptCompletionItemProvider.provideCompletionItems (/Users/daimor/.vscode/extensions/intersystems-community.vscode-objectscript-2.2.0/dist/extension.js:2:620714)
    at Y.provideCompletionItems (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:44775)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:64375
    at se.s (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:56458)
    ```

But works fine, when the Language Server extension is active, and It should be tied so much. Debugging, have to be fully functional without Language Server.

**Comment by isc-bsaviano** [comment]
The main extension uses the Language Server's `DocumentSymbolProvider` without checking if it's installed and active first. It should check that first and if the Language Server is not present it should find some other way to resolve a class breakpoint to a line.
