### ISSUE TITLE
Can't import and compile classes with 2.4.2

### ISSUE THREAD

**Issue by eduard93** [intersystems-community/vscode-objectscript#1070]
Pressing `import and compile` button on any local class/folder on version `2.4.2` causes this error:
```
[2023-02-02 12:15:40.498] [exthost] [error] TypeError: Cannot read properties of undefined (reading 'Deployed')
	at c:\Users\elebedyu\.vscode\extensions\intersystems-community.vscode-objectscript-2.4.2\dist\extension.js:2:708587
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async m (c:\Users\elebedyu\.vscode\extensions\intersystems-community.vscode-objectscript-2.4.2\dist\extension.js:2:448144)
	at async Promise.all (index 0)
	at async v (c:\Users\elebedyu\.vscode\extensions\intersystems-community.vscode-objectscript-2.4.2\dist\extension.js:2:452344)
	at async Promise.all (index 0)
	at async c._executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:63762) vscode-objectscript.compileFolder {"value":"intersystems-community.vscode-objectscript","_lower":"intersystems-community.vscode-objectscript"}
```

Reverting to `2.4.1` resolves this issue.

**Comment by gjsjohnmurray** [comment]
@eduard93 does the dev build linked to in https://github.com/intersystems-community/vscode-objectscript/issues/1068#issuecomment-1413242797 resolve this issue too?

**Comment by gjsjohnmurray** [comment]
@isc-bsaviano this may have been caused by #1054

@eduard93 does it make a difference whether or not the class already exists in the target namespace?

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray I'll fix this when I get into the office.
