### ISSUE TITLE
Language Server stop working when installed remotely

### ISSUE THREAD

**Issue by IRISMeister** [intersystems-community/vscode-objectscript#426]
I'm regularly using remote-ssh to connect to my Linux environment (VM/physical) from my Windows laptop.
https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh
ObjectScript extension works fine but Language Server complains at startup and stop working.
![remote](https://user-images.githubusercontent.com/12710874/96977396-00396980-1558-11eb-9dbd-294c2ac2bd2b.JPG)

Please note, localhost:52773[DEMO] is local to remote Linux environment, not to my Windows laptop.

**Comment by daimor** [comment]
Yes, it's already a known issue, reported here
https://github.com/intersystems/language-server/issues/32
You can disable language server extension for a while, and important to press later in the prompt, or install the [latest beta](https://github.com/intersystems-community/vscode-objectscript/releases) version of this extension

**Comment by IRISMeister** [comment]
Actually with 1.1.5, I'm getting different error messages.

```
node: malloc.c:2379: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
[Info  - 8:31:20 AM] Connection to server got closed. Server will restart.
[Error - 8:31:20 AM] Request textDocument/foldingRange failed.
Error: Connection got disposed.
	at Object.dispose (/home/iwamoto/.vscode-server/extensions/intersystems.language-server-1.1.5/client/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
	at Object.dispose (/home/iwamoto/.vscode-server/extensions/intersystems.language-server-1.1.5/client/node_modules/vscode-languageclient/lib/common/client.js:73:35)
	at LanguageClient.handleConnectionClosed (/home/iwamoto/.vscode-server/extensions/intersystems.language-server-1.1.5/client/node_modules/vscode-languageclient/lib/common/client.js:2424:42)
	at LanguageClient.handleConnectionClosed (/home/iwamoto/.vscode-server/extensions/intersystems.language-server-1.1.5/client/node_modules/vscode-languageclient/lib/node/main.js:155:15)
	at closeHandler (/home/iwamoto/.vscode-server/extensions/intersystems.language-server-1.1.5/client/node_modules/vscode-languageclient/lib/common/client.js:2411:18)
	at CallbackList.invoke (/home/iwamoto/.vscode-server/extensions/intersystems.language-server-1.1.5/client/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/home/iwamoto/.vscode-server/extensions/intersystems.language-server-1.1.5/client/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at closeHandler (/home/iwamoto/.vscode-server/extensions/intersystems.language-server-1.1.5/client/node_modules/vscode-jsonrpc/lib/common/connection.js:256:26)
	at CallbackList.invoke (/home/iwamoto/.vscode-server/extensions/intersystems.language-server-1.1.5/client/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/home/iwamoto/.vscode-server/extensions/intersystems.language-server-1.1.5/client/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at IPCMessageReader.fireClose (/home/iwamoto/.vscode-server/extensions/intersystems.language-server-1.1.5/client/node_modules/vscode-jsonrpc/lib/common/messageReader.js:40:27)
	at ChildProcess.<anonymous> (/home/iwamoto/.vscode-server/extensions/intersystems.language-server-1.1.5/client/node_modules/vscode-jsonrpc/lib/node/main.js:33:45)
	at ChildProcess.emit (events.js:327:22)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node: malloc.c:2379: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
[Info  - 8:31:21 AM] Connection to server got closed. Server will restart.
node: malloc.c:2379: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
[Info  - 8:31:21 AM] Connection to server got closed. Server will restart.
node: malloc.c:2379: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
[Info  - 8:31:22 AM] Connection to server got closed. Server will restart.
node: malloc.c:2379: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
[Error - 8:31:22 AM] Connection to server got closed. Server will not be restarted.
```
