### ISSUE TITLE
Beta version of extension fails to activate on Insiders

### ISSUE THREAD

**Issue by isc-bsaviano** [intersystems-community/vscode-objectscript#793]
Previously, a beta version of this extension could be used in Insiders and it would be activated with the proposed API enabled automatically. However, on the latest Insiders, activating a beta version fails with these errors:

In the Window Log:

> [2021-12-01 09:03:36.707] [renderer3] [critical] Extension 'intersystems-community.vscode-objectscript CANNOT USE these API proposals 'fileSearchProvider, textSearchProvider'. You MUST start in extension development mode or use the --enable-proposed-api command line flag

In the Extension Host Log:

> [2021-12-01 09:03:40.455] [exthost] [error] Activating extension intersystems-community.vscode-objectscript failed due to an error:
[2021-12-01 09:03:40.455] [exthost] [error] Error: Extension 'intersystems-community.vscode-objectscript' CANNOT use API proposal: fileSearchProvider.
Its package.json#enabledApiProposals-property declares:  but NOT fileSearchProvider.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api intersystems-community.vscode-objectscript
	at w (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:93:80837)
	at Object.registerFileSearchProvider (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:37507)
	at t.activate (/Users/bsaviano/.vscode-insiders/extensions/intersystems-community.vscode-objectscript-1.1.2-dev.792/dist/extension.js:1:441960)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async Promise.all (index 0)

Adding this line to my Insiders' argv.json fixes the issue:

```json
"enable-proposed-api": ["intersystems-community.vscode-objectscript"]
```

I'm not sure if this is an issue with our extension or a VS Code change that we weren't aware of.

**Comment by gjsjohnmurray** [comment]
Maybe something changed as part of the refactoring to give finer granularity to proposed API enablement.

I suggest you update our README to state explicitly that the argv.json setting is needed by Insiders as well as Stable.
